using System.Collections.Concurrent;
using System.Runtime.InteropServices;
using Heimdall.Core.FileSystem;

namespace Heimdall.Windows;

/// <summary>
/// Copy, move, delete and rename for Windows. Everything destructive routes
/// through here so there is exactly one place to get right.
///
/// **<see cref="Trash"/> is not implemented, and fails rather than deleting.**
/// That is the single most important line in this file. There is no BCL API for
/// the Recycle Bin — it needs SHFileOperation or IFileOperation, both P/Invoke
/// or COM under NativeAOT — and the tempting shortcut is to make Delete stand in
/// for it. Deleting a file the user asked to be able to get back is not a
/// degraded version of trashing it; it is the one outcome the trash exists to
/// prevent. So it reports a failure the UI can show, and the user still has
/// their file.
/// </summary>
public sealed class WindowsFileOperations : IFileOperations
{
    private const int BufferSize = 1 << 20;

    private readonly ConcurrentStack<IUndoable> _undo = new();

    /// <summary>
    /// Tags are keyed by path here, unlike the Linux extended attributes that
    /// ride along with the file, so the operations that change a path have to
    /// tell the index. Null is allowed so the operations remain testable on
    /// their own.
    /// </summary>
    private readonly WindowsTagStore? _tags;

    public WindowsFileOperations(WindowsTagStore? tags = null) => _tags = tags;

    public bool CanUndo => !_undo.IsEmpty;

    public IOperationHandle Copy(
        IReadOnlyList<string> sources, string destination,
        Func<string, ValueTask<ConflictResolution>> onConflict)
        => Run(sources, destination, onConflict, move: false);

    public IOperationHandle Move(
        IReadOnlyList<string> sources, string destination,
        Func<string, ValueTask<ConflictResolution>> onConflict)
        => Run(sources, destination, onConflict, move: true);

    /// <summary>
    /// The Recycle Bin, via SHFileOperation.
    ///
    /// **SHFileOperation rather than IFileOperation**, which is the supported
    /// modern route and is COM. WINDOWS.md §6 warns that COM under NativeAOT is
    /// the risky combination and needs source-generated interop or it fails at
    /// runtime rather than at build time. This call is one struct and one
    /// function, source-generated by `LibraryImport` and AOT-clean today.
    /// IFileOperation buys progress and collision UI we do not use here, since
    /// <see cref="OperationHandle"/> already reports progress.
    ///
    /// **FOF_WANTNUKEWARNING is load-bearing, not decoration.** With
    /// FOF_ALLOWUNDO alone, a file too large for the bin — or any file when the
    /// bin is disabled for that drive — is *permanently deleted*, silently,
    /// because FOF_NOCONFIRMATION suppressed the question Explorer would have
    /// asked. WANTNUKEWARNING partially overrides NOCONFIRMATION for exactly
    /// that case: ordinary recycling stays silent, and destruction still has to
    /// be agreed to. Removing it turns this method into <see cref="Delete"/>
    /// without saying so.
    /// </summary>
    public IOperationHandle Trash(IReadOnlyList<string> paths)
    {
        var handle = new OperationHandle();

        _ = Task.Run(() =>
        {
            nint from = 0;

            try
            {
                handle.Begin(paths.Count, totalBytes: 0);

                // SHFileOperation wants absolute paths — a relative one is
                // resolved against the process's working directory, which is
                // not the folder being listed.
                var full = paths.Select(Path.GetFullPath).ToList();

                from = Native.DoubleNullTerminated(full);

                var operation = new Native.SHFILEOPSTRUCTW
                {
                    wFunc = Native.FO_DELETE,
                    pFrom = from,
                    fFlags = Native.FOF_ALLOWUNDO
                           | Native.FOF_NOCONFIRMATION
                           | Native.FOF_WANTNUKEWARNING
                           | Native.FOF_SILENT
                           | Native.FOF_NOERRORUI,
                };

                var status = Native.SHFileOperation(ref operation);

                // Aborted covers the user declining the nuke warning, which is
                // a cancellation rather than a failure — nothing was deleted and
                // nothing went wrong.
                if (operation.fAnyOperationsAborted != 0)
                {
                    handle.Cancelled();
                    return;
                }

                if (status != 0)
                {
                    handle.Failed(new IOException(
                        $"The Recycle Bin refused the operation (SHFileOperation returned {status})."));
                    return;
                }

                handle.ItemFinished();
                handle.Complete();
            }
            catch (Exception ex)
            {
                handle.Failed(ex);
            }
            finally
            {
                if (from != 0) Marshal.FreeHGlobal(from);
            }
        });

        return handle;

        // **Not undoable from here, deliberately.** The bin knows where each
        // item came from and Explorer can put it back; this application cannot,
        // because SHFileOperation reports no handle for what it recycled.
        // Pushing an undo entry that cannot restore would make Ctrl+Z claim a
        // success it did not have. Restore is ITrashMaintenance's job and needs
        // the shell namespace — which is the COM decision still outstanding.
    }

    /// <summary>
    /// Irreversible. Only ever reached from an explicit, separate user action —
    /// never as the default for the Delete key.
    /// </summary>
    public IOperationHandle Delete(IReadOnlyList<string> paths)
    {
        var handle = new OperationHandle();

        _ = Task.Run(async () =>
        {
            try
            {
                handle.Begin(paths.Count, totalBytes: 0);

                foreach (var path in paths)
                {
                    handle.Token.ThrowIfCancellationRequested();
                    await handle.WaitIfPausedAsync().ConfigureAwait(false);

                    handle.ItemStarted(path);

                    // A read-only file refuses to delete on Windows where it
                    // would go on Linux, because the permission is on the file
                    // rather than its directory. The user asked for it to go.
                    ClearReadOnly(path);

                    if (Directory.Exists(path)) Directory.Delete(path, recursive: true);
                    else File.Delete(path);

                    // Only after the delete succeeded, and only for a permanent
                    // one — a recycled file can come back, and forgetting its
                    // tags would mean restoring it from Explorer returned an
                    // untagged file.
                    _tags?.Forget(path);

                    handle.ItemFinished();
                }

                handle.Complete();
            }
            catch (OperationCanceledException) { handle.Cancelled(); }
            catch (Exception ex) { handle.Failed(ex); }
        });

        return handle;
    }

    private static void ClearReadOnly(string path)
    {
        try
        {
            var attributes = File.GetAttributes(path);
            if ((attributes & FileAttributes.ReadOnly) != 0)
                File.SetAttributes(path, attributes & ~FileAttributes.ReadOnly);
        }
        catch (Exception e) when (e is IOException or UnauthorizedAccessException)
        {
            // Let the delete itself report the problem.
        }
    }

    public ValueTask RenameAsync(string path, string newName, CancellationToken ct)
    {
        // Both separators, because both are legal here — the same reason
        // PathRules unifies them.
        if (string.IsNullOrWhiteSpace(newName)
            || newName.Contains(Path.DirectorySeparatorChar)
            || newName.Contains(Path.AltDirectorySeparatorChar))
            throw new ArgumentException(
                "A name cannot be empty or contain a separator.", nameof(newName));

        var directory = PathRules.Parent(Path.GetFullPath(path))
            ?? throw new IOException("A drive root cannot be renamed.");

        var target = Path.Combine(directory, newName);

        if (PathRules.Same(target, path)) return ValueTask.CompletedTask;

        // Case-insensitively, so renaming "readme" to "README" is not rejected
        // as already existing — it is the same file, and the rename is exactly
        // how a user fixes the case of a name.
        if ((File.Exists(target) || Directory.Exists(target))
            && !string.Equals(target, path, StringComparison.OrdinalIgnoreCase))
            throw new IOException($"'{newName}' already exists here.");

        if (Directory.Exists(path)) Directory.Move(path, target);
        else File.Move(path, target, overwrite: false);

        // Before the undo entry, so a rename that is immediately undone leaves
        // the index where it started rather than one step behind.
        _tags?.Retarget(path, target);

        _undo.Push(new UndoRename(target, path, _tags));
        return ValueTask.CompletedTask;
    }

    public async ValueTask UndoAsync(CancellationToken ct)
    {
        if (_undo.TryPop(out var action))
            await action.UndoAsync(ct).ConfigureAwait(false);
    }

    private IOperationHandle Run(
        IReadOnlyList<string> sources, string destination,
        Func<string, ValueTask<ConflictResolution>> onConflict, bool move)
    {
        var handle = new OperationHandle();

        _ = Task.Run(async () =>
        {
            try
            {
                // Enumerating first means the progress bar is honest from the
                // start rather than discovering the total as it goes.
                var plan = BuildPlan(sources, destination, handle.Token);
                handle.Begin(plan.Count, plan.Sum(p => p.Length));

                var created = new List<string>();

                foreach (var item in plan)
                {
                    handle.Token.ThrowIfCancellationRequested();
                    await handle.WaitIfPausedAsync().ConfigureAwait(false);

                    var target = item.Target;

                    if (File.Exists(target) || Directory.Exists(target))
                    {
                        switch (await onConflict(target).ConfigureAwait(false))
                        {
                            case ConflictResolution.Skip:
                                handle.ItemFinished();
                                continue;
                            case ConflictResolution.KeepBoth:
                                target = Deduplicate(target);
                                break;
                            case ConflictResolution.Cancel:
                                throw new OperationCanceledException();
                            case ConflictResolution.Overwrite:
                                break;
                        }
                    }

                    handle.ItemStarted(item.Source);
                    Directory.CreateDirectory(PathRules.Parent(target) ?? destination);

                    if (item.IsDirectory)
                    {
                        Directory.CreateDirectory(target);
                    }
                    else
                    {
                        await CopyFileAsync(item.Source, target, handle).ConfigureAwait(false);
                        if (move)
                        {
                            ClearReadOnly(item.Source);
                            File.Delete(item.Source);
                        }
                    }

                    created.Add(target);
                    handle.ItemFinished();
                }

                // Directories are removed only after their contents moved, so a
                // cancelled move never deletes a folder it has not emptied.
                if (move)
                {
                    foreach (var source in sources.Where(Directory.Exists).Reverse())
                        if (Directory.Exists(source)
                            && !Directory.EnumerateFileSystemEntries(source).Any())
                            Directory.Delete(source);
                }

                // Per top-level source, not per planned item: Retarget already
                // follows everything beneath a folder, so moving a tagged tree
                // costs one call rather than one per file in it.
                if (move)
                    foreach (var source in sources)
                        _tags?.Retarget(
                            source,
                            Path.Combine(destination, PathRules.LeafName(Path.GetFullPath(source))));

                // Copies are not undoable: undoing one means deleting files,
                // and an undo that deletes is not a safe default.
                if (move && created.Count > 0)
                    _undo.Push(new UndoMove(sources, destination, _tags));

                handle.Complete();
            }
            catch (OperationCanceledException) { handle.Cancelled(); }
            catch (Exception ex) { handle.Failed(ex); }
        });

        return handle;
    }

    /// <summary>
    /// **Windows' convention, not freedesktop's.** XdgTrash.Deduplicate produces
    /// "file (1).txt"; Explorer produces "file - Copy.txt" and then
    /// "file - Copy (2).txt". WINDOWS.md flagged this as the one place a
    /// platform helper was misleadingly named — the rule differs, so the code
    /// does too rather than being shared.
    /// </summary>
    internal static string Deduplicate(string target)
    {
        var directory = PathRules.Parent(target);
        if (directory is null) return target;

        var stem = Path.GetFileNameWithoutExtension(target);
        var extension = Path.GetExtension(target);

        var candidate = Path.Combine(directory, $"{stem} - Copy{extension}");

        for (var n = 2; File.Exists(candidate) || Directory.Exists(candidate); n++)
            candidate = Path.Combine(directory, $"{stem} - Copy ({n}){extension}");

        return candidate;
    }

    private static List<PlannedItem> BuildPlan(
        IReadOnlyList<string> sources, string destination, CancellationToken ct)
    {
        var plan = new List<PlannedItem>();

        foreach (var source in sources)
        {
            ct.ThrowIfCancellationRequested();
            var full = Path.GetFullPath(source);
            var name = PathRules.LeafName(full);

            if (Directory.Exists(full))
            {
                var root = Path.Combine(destination, name);
                plan.Add(new PlannedItem(full, root, 0, IsDirectory: true));

                foreach (var dir in Directory.EnumerateDirectories(full, "*", SearchOption.AllDirectories))
                    plan.Add(new PlannedItem(dir, Path.Combine(root, Path.GetRelativePath(full, dir)), 0, true));

                foreach (var file in Directory.EnumerateFiles(full, "*", SearchOption.AllDirectories))
                {
                    var length = new FileInfo(file).Length;
                    plan.Add(new PlannedItem(
                        file, Path.Combine(root, Path.GetRelativePath(full, file)), length, false));
                }
            }
            else if (File.Exists(full))
            {
                plan.Add(new PlannedItem(
                    full, Path.Combine(destination, name), new FileInfo(full).Length, false));
            }
        }

        return plan;
    }

    private static async Task CopyFileAsync(string source, string target, OperationHandle handle)
    {
        var buffer = new byte[BufferSize];

        await using var input = new FileStream(
            source, FileMode.Open, FileAccess.Read, FileShare.Read, BufferSize, useAsync: true);
        await using var output = new FileStream(
            target, FileMode.Create, FileAccess.Write, FileShare.None, BufferSize, useAsync: true);

        int read;
        while ((read = await input.ReadAsync(buffer, handle.Token).ConfigureAwait(false)) > 0)
        {
            await handle.WaitIfPausedAsync().ConfigureAwait(false);
            await output.WriteAsync(buffer.AsMemory(0, read), handle.Token).ConfigureAwait(false);
            handle.BytesCopied(read);
        }
    }

    private readonly record struct PlannedItem(
        string Source, string Target, long Length, bool IsDirectory);

    private interface IUndoable
    {
        ValueTask UndoAsync(CancellationToken ct);
    }

    private sealed class UndoRename(
        string current, string original, WindowsTagStore? tags) : IUndoable
    {
        public ValueTask UndoAsync(CancellationToken ct)
        {
            if (Directory.Exists(current)) Directory.Move(current, original);
            else if (File.Exists(current)) File.Move(current, original, overwrite: false);
            else return ValueTask.CompletedTask;

            tags?.Retarget(current, original);
            return ValueTask.CompletedTask;
        }
    }

    private sealed class UndoMove(
        IReadOnlyList<string> sources, string destination, WindowsTagStore? tags) : IUndoable
    {
        public ValueTask UndoAsync(CancellationToken ct)
        {
            foreach (var source in sources)
            {
                var name = PathRules.LeafName(Path.GetFullPath(source));
                var moved = Path.Combine(destination, name);

                tags?.Retarget(moved, source);

                if (File.Exists(moved))
                {
                    // File.Move copes with a different volume; Directory.Move
                    // does not, which is why the two are not one call.
                    File.Move(moved, source, overwrite: false);
                }
                else if (Directory.Exists(moved))
                {
                    MoveDirectory(moved, source);
                }
            }

            return ValueTask.CompletedTask;
        }

        private static void MoveDirectory(string from, string to)
        {
            if (string.Equals(Path.GetPathRoot(from), Path.GetPathRoot(to),
                              StringComparison.OrdinalIgnoreCase))
            {
                Directory.Move(from, to);
                return;
            }

            // Across volumes, by hand. Directory.Move throws IOException rather
            // than falling back, and an undo that reports failure after the move
            // succeeded is worse than doing the copy.
            Directory.CreateDirectory(to);

            foreach (var directory in Directory.EnumerateDirectories(from, "*", SearchOption.AllDirectories))
                Directory.CreateDirectory(Path.Combine(to, Path.GetRelativePath(from, directory)));

            foreach (var file in Directory.EnumerateFiles(from, "*", SearchOption.AllDirectories))
                File.Copy(file, Path.Combine(to, Path.GetRelativePath(from, file)), overwrite: true);

            Directory.Delete(from, recursive: true);
        }
    }
}
